spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  main:
    allow-circular-references: false
  debug: true

server:
  port: 8081

kafka:
  bootstrap-servers: localhost:9092
